export interface TdaQuestion {
  id: number;
  question: string;
  questionEn: string;
  options: { [key: string]: string };
  optionsEn: { [key: string]: string };
  answer: string;
  multiSelect: boolean;
}

export const TDA_QUIZ_DATA: TdaQuestion[] = [
  {
    id: 1,
    question: "德州撲克中,玩家 C 在轉牌圈時將兩張底牌用籌碼壓住。A 開注 5000,B 跟注,C 加注到總額 15000。D 棄牌。發牌員收 D 的牌時不慎把 D 的牌與 C 的牌混在一起。此時 A 還沒跟 C 的加注。TD 應如何處理?",
    questionEn: "In Texas Holdem Player C has his 2 downcards under a chip protector. On the turn A opens for 5000. B calls and C raises to 15000 total. D folds. As the dealer sweeps D's downcards he accidentally mixes them with C's downcards. A has not yet called C's raise. How should the TD handle this?",
    options: {
      "A": "玩家有義務保護自己的手牌,但若發牌員誤殺手牌,該玩家所下的任何注(跟注或加注)應退回。本題中 C 的手牌作廢,15000 全額退還給 C。",
      "B": "C 應該保護自己的手牌。他的手牌作廢,所下注全部沒收。",
      "C": "C 應該保護自己的手牌。手牌作廢,注全部沒收,但 10000 的加注部分退還給他。",
      "D": "C 已用籌碼保護手牌,有權全額拿回所下注。",
    },
    optionsEn: {
      "A": "Players should protect their hands, but if the dealer kills a hand by mistake, any bet (call or raise) by that player will be returned. In this case, C's hand is dead, and his full 15000 bet is refunded to him.",
      "B": "C should have protected his hand. His hand is dead and he has forfeited all of his bets.",
      "C": "C should have protected his hand. C's hand is dead and his bets are forfeited. His 10000 raise will be returned to him.",
      "D": "C protected his hand with a card protector and is entitled to a return of all his bets.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 2,
    question: "底池限注奧瑪哈高低牌(Pot-Limit Omaha 8 or better),盲注 500/1000。翻牌後 A 開注 1500,B 跟注,C 加注至總額 4000。玩家 D 有哪些選項?",
    questionEn: "In pot-limit Omaha 8 or better, blinds are 500/1000. Postflop Player A opens betting for 1500. B calls and C raises to 4000 total. What are Player D's options?",
    options: {
      "A": "D 可跟注 4000、棄牌,或加注至底池總額(不含自己 4000 跟注部分)。",
      "B": "D 可跟注 4000、棄牌,或加注至上限。",
      "C": "D 可跟注 4000。若要加注,因為是底池限注,必須加注底池全額。",
      "D": "因為 C 加注了 2500,D 可跟注 4000、棄牌,或加注至至少 6500 總額。",
    },
    optionsEn: {
      "A": "D can call the 4000, fold, or raise up to the total amount of chips in the pot not including his 4000 call.",
      "B": "D can call the 4000, fold, or raise up to the total amount of chips in the pot including his 4000 call.",
      "C": "D may call the 4000. If he wants to raise he must raise the total amount in the pot because it is a pot-limit game.",
      "D": "Because C raised 2500, D can call the 4000, fold, or raise to at least 6500 total.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 3,
    question: "在河牌最後行動位置時,手持nuts(最大牌)未下注,自動視為消極對局(soft play)。是犯規行為",
    questionEn: "Not betting the nuts when last to act on the river is an automatic finding of soft play",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 4,
    question: "在德州撲克中,玩家面對一筆下注。思考了一段時間後,他不發一語地把一張或多張底牌正面朝上亮在自己面前。這是有約束力的棄牌動作。",
    questionEn: "In holdem, a player faces a bet. He thinks awhile then silently exposes one or more of his downcards face up in front of him. This is a binding fold.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 5,
    question: "TD 對玩家處以「跳過 1 輪」的處罰(missed penalty)。該玩家可以留在桌上,但處罰期間不會發牌到他的座位。",
    questionEn: "The TD puts a player on a 1 round missed penalty. The player may remain at the table but cards will not be dealt to his seat during the penalty phase.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 6,
    question: "要從一張開放桌移動一名玩家到另一張開放桌以平衡桌數時,應該移動哪一位玩家?",
    questionEn: "When selecting a player to move from one open table to another to \"balance\" the two tables, which player should be moved?",
    options: {
      "A": "目前正坐在 Button 位置的玩家,在打完本手後被移動。",
      "B": "為了確保隨機性,TD 使用隨機號碼系統決定要被移動的座位。",
      "C": "下一手將是大盲(且本手尚未當過大盲)的玩家移到新桌。",
      "D": "目前是大盲的玩家,打完大盲這手後、進入下一手的小盲之前被移動。",
    },
    optionsEn: {
      "A": "The player who is on the button this hand will be moved once he has completed the current hand.",
      "B": "To assure randomness, the TD will use a random number system to decide the seat to be moved.",
      "C": "The player who will be big blind next (but has not yet had the BB) will be moved to the new table.",
      "D": "The player who is the big blind will be moved after he has completed the hand as the big blind and before he starts as the small blind of the next hand.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 7,
    question: "在攤牌時,玩家決定把手牌正面朝下推向前棄掉。牌仍 100% 可辨識且可取回,也沒有碰到棄牌堆。但只要做出「正面朝下推向前」這個動作,牌就立即作廢。",
    questionEn: "At showdown a player decides to discard his hand by pushing his cards forward face down. The cards are still 100% identifiable and retrievable and are not touching the muck. However they are dead because the act of pushing the cards forward face down immediately kills the cards.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 8,
    question: "如果玩家還有活著的手牌,但決定離座去跟欄杆外的朋友擊掌(high-5),手牌會自動作廢,所下注沒收。",
    questionEn: "If a player has a live hand but decides to leave his or her seat and \"high-5\" with friends on the rail, the hand will automatically be killed and the player's bets forfeited.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 9,
    question: "玩家 A、B、C 進入攤牌。沒有任何玩家全下。C 亮出一手強牌,A 與 B 決定直接把牌正面朝下棄掉(不亮牌)。A 認為 B 的牌可能是壞牌(fouled hand),要求看 B 的牌。TD 應如何回應 A 的要求?",
    questionEn: "Player A, B, and C go to showdown. No player is all-in. Player C reveals a strong hand and A and B decide to muck their cards face down without tabling them. Player A thinks B has a fouled hand and requests to see B's cards. How should the TD respond to A's request?",
    options: {
      "A": "要求看牌是一種特權,若 A 對 B 的牌有合理懷疑,TD 可以批准。",
      "B": "只要有任何玩家(無論是否在牌局中)懷疑某玩家的牌是壞牌,TD 必須立即把該手牌亮出來,沒有例外。",
      "C": "要求看牌是一種特權,除非 TD 認為 A 的理由完全沒有根據,否則必須批准。",
      "D": "因為 A 在攤牌時沒有亮出自己的牌、已經正面朝下棄牌,他喪失要求看任何牌的權利或特權。",
    },
    optionsEn: {
      "A": "Asking to see a hand is a privilege which the TD may grant if A has a reasonable suspicion about B's hand.",
      "B": "If any player in the hand or not suspects another player's hand is fouled, the TD must table that hand immediately without exception.",
      "C": "Asking to see a hand is a privilege which the TD must grant unless he thinks A's reason has no merit at all.",
      "D": "Because A did not table his hand at showdown and his cards have been mucked face down, he loses any right or privilege to ask to see any hand.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 10,
    question: "若有人要求計時(call the clock),TDA 規則規定在最後倒數開始前,要先給一段固定時間。這個固定時間不可由 TD 自行調整。",
    questionEn: "If the clock is called for, the TDA Rules provide for a fixed amount of time before the final countdown begins. This fixed amount of time may not be adjusted by the TD.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 11,
    question: "玩家面對一筆巨額全下,正在考慮是否跟注。另一玩家要求計時,TD 批准。下列哪一個裁決最符合 TDA 對此情況的指導原則?",
    questionEn: "A player faces a huge all-in bet and is taking time to decide whether to call. A player calls for the clock and the TD approves the request. Which ruling best follows TDA guidelines for this situation?",
    options: {
      "A": "30 秒過後,TD 倒數 10 秒。TD 剛數完最後一秒、但還沒口頭宣告手牌作廢前,玩家說「Call」。這是有效的跟注。",
      "B": "TD 給玩家最多 25 秒,加上 5 秒倒數。若在倒數結束前未行動,手牌作廢。",
      "C": "從要求計時起算 30 秒,若 30 秒結束時玩家還沒行動,手牌作廢。",
      "D": "1 分鐘過後 TD 倒數 10 秒,然後宣告「你的手牌作廢」。手牌在 10 秒倒數結束時作廢,宣告只是形式。",
    },
    optionsEn: {
      "A": "After a 30-second period expires, the TD counts down 10 seconds. After the TD has just finished counting the last second but before verbally declaring the hand dead the player says \"I Call\". This is a valid call.",
      "B": "The TD will give the player up to 25 seconds plus a 5-second countdown to act. If he does not act before the end of the count, his hand is dead.",
      "C": "A 30 second period starts when the clock is called for, if the player has not acted at the end of 30 seconds following call for the clock, the hand is dead.",
      "D": "A one-minute period expires and the TD counts down 10 seconds then declares \"your hand is dead\". The hand is dead at the end of the 10 second countdown. The declaration is a formality.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 12,
    question: "底池限注奧瑪哈高低牌(Pot-Limit Omaha 8 or better),盲注 1000/2000。轉牌後 A 開注 3500。B 不發一語推出 8 個籌碼:兩個 1000、六個 500(總共 5000)。B 的下注是多少?C 面對的行動是什麼?",
    questionEn: "In Pot-Limit Omaha 8 or better, blinds are 1000/2000. On the turn Player A opens for 3500. B silently pushes out 8 chips: two 1000's, and six 500 chips (5000 total). What is B's bet and what is the action to Player C?",
    options: {
      "A": "最小加注為再加 3500。B 不發一語推出總額 5000,多出 1500。1500 不到最小加注 3500 的 50%。B 沒口頭宣告加注,所以視為跟注。C 面對的金額為 3500。",
      "B": "B 推出超過最小加注的 50%。最小加注是再加 2000(大盲額度),B 多推 1500 超過 2000 的 50%,所以必須補成完整加注。C 面對 5500。",
      "C": "這是有約束力的加注動作。B 必須把總下注補到 7000(最小加注額)。C 面對 7000。",
    },
    optionsEn: {
      "A": "The min raise is 3500 more; B put out 5000 total silently which is 1500 more. 1500 is less than 50% of the 3500 min-raise. B didn't declare raise so this is a call. It's 3500 to C.",
      "B": "B put out more than 50% of a min raise. The min raise is 2000 more (the BB amount); B put out 1500 which is more than 50% of 2000 so he must make a full raise. It's 5500 to C.",
      "C": "This is a binding gesture to raise. B must increase his total bet to 7000 (the minimum raise). It is 7000 to C.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 13,
    question: "對於一手牌結果的異議權,何時終止?",
    questionEn: "When does the right to dispute the outcome of a hand end?",
    options: {
      "A": "當所有牌都進入棄牌堆且底池已分配時。",
      "B": "直到下一手牌發生有效動作(substantial action)為止。",
      "C": "當下一手開始洗牌的第一次切牌(riffle)時。",
      "D": "牌型解讀的異議期到下一手洗牌的第一次切牌為止;底池計算的異議期到下一手發生有效動作為止。",
    },
    optionsEn: {
      "A": "When the cards are all mucked and the pot has been awarded.",
      "B": "Until substantial action on the next hand.",
      "C": "When the next hand begins with the first riffle of the cards.",
      "D": "Reading the hands may be disputed until the first riffle of cards for the next hand. The pot count may be disputed until substantial action on the next hand.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 14,
    question: "在 6 人桌賽事(如 6 人桌德州撲克)中,決賽桌會從 7 名玩家開始。",
    questionEn: "In a 6-handed game (such as 6-handed Holdem), the final table will start with 7 players.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 15,
    question: "無限注德州撲克翻牌後,A 行動,他宣告「我下注底池金額」。應如何處理?",
    questionEn: "In no-limit Texas Holdem, post flop action is on Player A who declares \"I bet the amount currently in the pot\", how should this be handled?",
    options: {
      "A": "A 已承諾要下注,底池不予計算。A 必須宣告一個明確金額的合法下注,可能被警告或處罰。",
      "B": "由於此不當宣告,A 失去主動行動的權利,只能過牌(check),不可主動下注,且可能被警告或處罰。",
      "C": "這是嘴砲(trash talk),荷官可以忽略。荷官應該問 A 要過牌還是下注。若 A 持續嘴砲,TD 可依情況警告或處罰。",
      "D": "為了賽局最佳利益,應該計算底池,且 A 必須下注與底池等額的金額。",
    },
    optionsEn: {
      "A": "A has committed to making a bet. The pot will not be counted. A must make a valid bet of a specific amount. He may be subject to warning or penalty.",
      "B": "A loses his right to initiate action by making this improper declaration. A can only check. He may not initiate a bet and is subject to warning or penalty.",
      "C": "This is trash talk that can be ignored by the dealer. The dealer should ask A if they want to check or bet. If A persists with trash-talking the TD may warn or penalize him as conditions warrant.",
      "D": "In the best interest of the game, the pot should be counted and Player A must make a bet equal to the pot size.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 16,
    question: "玩家面對下注遲遲未行動,有人要求計時。所給時間結束後,TD 進行 5 秒倒數。就在 TD 正要喊最後一個數字時,玩家說「Call」。很難判斷哪個先發生。應如何處理?",
    questionEn: "A player faces a bet and is slow to act and the clock is called. The allotted time expires and the TD delivers a 5 second countdown. Just as the TD is saying the last number in the count, the player says \"call\". It is difficult to say which came first. What should happen?",
    options: {
      "A": "若不能明確判定玩家是否搶在計時結束前出聲,則手牌作廢。",
      "B": "這種情況必須用隨機方式:荷官從棄牌堆隨機抽出 2 張牌,TD 先翻一張、再翻另一張。若大牌先翻則視為跟注,大牌後翻則手牌作廢。",
      "C": "若不確定,平手判給玩家。這是有效的跟注。",
      "D": "TD 應詢問桌上玩家與荷官,多數人認為玩家及時行動則視為跟注,否則手牌作廢。",
    },
    optionsEn: {
      "A": "If it is not clear that the player beat the clock, the hand is dead.",
      "B": "The random method must be used in these situations: The dealer will select 2 cards randomly from the discards. The TD will turn over one card first, then the other. If the higher card is turned over first, it's a call. If the higher card is turned last, the hand is dead.",
      "C": "If uncertain, a tie goes to the player. This is a legitimate call.",
      "D": "The TD should poll the players and dealer. If a majority say the player acted in time it's a call, otherwise the hand is dead.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 17,
    question: "賽事在科羅拉多州舉辦。桌上可使用哪些語言?",
    questionEn: "A tournament is being held in Colorado. What languages are acceptable at the table?",
    options: {
      "A": "任何已公告並宣布為可使用的語言。",
      "B": "任何語言皆可。規範口頭交流不是 TD 的責任。",
      "C": "只能使用該州最廣泛使用的語言。",
    },
    optionsEn: {
      "A": "Any language(s) that have been posted and announced as acceptable",
      "B": "Any language. It's not the TD's responsibility to regulate verbal communication",
      "C": "Only the most widely spoken language in the State",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 18,
    question: "牌局只剩兩名玩家。轉牌時 A 宣告「all-in」並推出 4 疊籌碼。B 籌碼比 A 多,B 詢問 A 推了多少,A 回答「42,500」。B 跟注。亮牌、發河牌,A 贏。精準計算後發現 A 實際推出 47,500 而非 42,500。下列哪一項最能說明 B 應補多少才能跟到 A 的下注?",
    questionEn: "Two players remain in the hand. On the turn Player A declares \"all-in\" then pushes out 4 stacks of chips. B has A covered but asks how much A pushed out. A replies \"42,500\". B calls. Cards are tabled, the river dealt, and A wins. The precise count finds A has pushed out 47,500 not 42,500. Which of the following best describes how much B must pay to cover A's bet?",
    options: {
      "A": "對手的計算是非官方的,所以 B 必須付足 47,500。若是荷官說 42,500,則 B 只需付 42,500。",
      "B": "B 既已接受對手的全下,必須付足 47,500。跟注者有責任在跟注前確認下注金額。",
      "C": "B 曾向對手詢問金額,被告知 42,500,所以付 42,500 即可。",
    },
    optionsEn: {
      "A": "An opponent's count is unofficial so B must pay the full 47,500. If the dealer had counted 42,500 then B would only owe 42,500.",
      "B": "Player B accepted the opponent's all-in action and must pay the full 47,500. It is the caller's responsibility to determine the correct amount of the bet before calling.",
      "C": "Player B asked the opponent for a count and was told 42,500. He must pay 42,500.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 19,
    question: "在德州撲克中,當決賽桌從 3 名玩家剩到 2 名時,Button 必須移動。這偶爾會使某名玩家連續兩手都是大盲。",
    questionEn: "In Texas Holdem, when the final table moves from 3 players to 2, the button must move. This may occasionally mean that a player will have the BB twice in a row.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 20,
    question: "賽事為德州撲克,盲注 50/100。A 與 B 各下小盲、大盲。所有起手牌已發。C 棄牌,D 跟注大盲,已發生有效動作。輪到 Button 位玩家時,他發現自己只有 1 張牌,在行動前告訴荷官。Button 的手牌應如何處理?",
    questionEn: "Game is THE, 50-100 blinds. Players A and B post SB and BB respectively. All initial cards are dealt. Player C folds, Player D calls the BB. Substantial action has occurred. Action reaches the button who realizes he has only 1 card and tells the dealer before acting. What happens to the buttons' hand?",
    options: {
      "A": "所有玩家一視同仁。因已發生有效動作,手牌作廢,但 Button 所付的底注退還。",
      "B": "只要 Button 還沒行動,就從牌堆最上方發一張作為第二張底牌。",
      "C": "起手發牌時手牌不足是有效動作規則的例外,必須宣告誤發牌(misdeal)。",
      "D": "任何玩家若起手牌數不對,應在有效動作發生前提出,否則手牌作廢。",
    },
    optionsEn: {
      "A": "All players are treated the same, because substantial action occurred the hand is dead, however any ante the button made will be returned to him or her.",
      "B": "As long as the button does not first act on his hand, he will be dealt the top card off the stub as his second card.",
      "C": "A player with too few cards on the initial deal is an exception to the substantial action rule. A misdeal must be declared.",
      "D": "Any player who does not have the correct # of cards should announce it before substantial action occurs, otherwise their hand is dead.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 21,
    question: "下列哪些是規則中明定的玩家責任?(複選)",
    questionEn: "Which of the following are stated player responsibilities?",
    options: {
      "A": "確認自己的報名資料",
      "B": "保護自己的手牌",
      "C": "跟上行動(注意誰該行動、誰已行動)",
      "D": "自選座位(先到先選)",
    },
    optionsEn: {
      "A": "Verifying registration data",
      "B": "Protecting their hands",
      "C": "Follow the action",
      "D": "Choosing their own seat, it's first come, first served",
    },
    answer: "ABC",
    multiSelect: true,
  },
  {
    id: 22,
    question: "3 名玩家持續建立大底池。河牌時 A 下注 100,000,B 加注至總額 350,000。C 思考一陣後將一張底牌翻開(是一張 A),並對 B 說「我知道你贏我了」。TD 被叫到桌前,應如何裁決?",
    questionEn: "3 players are building a large pot. On the river, A bets 100,000. B raises to 350,000 total. C thinks awhile then turns one downcard face up (an Ace) and says to B: \"I know you've got me beat\". The TD is called to the table. How should he rule?",
    options: {
      "A": "C 在行動未完成時故意露牌,不論是否口頭宣告棄牌,手牌都作廢。",
      "B": "露牌本身不會殺死他的手牌,但他已口頭明確宣告棄牌。手牌作廢。",
      "C": "C 只露一張不是全部手牌,可繼續打,但會受罰。若露出全部底牌,則手牌作廢。",
      "D": "C 露牌後必須帶著這個缺陷繼續打。可跟注、加注、或棄牌,且可能被處罰。",
    },
    optionsEn: {
      "A": "C deliberately exposed a card with action pending therefore his hand is dead, with or without any verbal statement of folding.",
      "B": "C's card exposure does not kill his hand but he has verbally declared a clear fold. His hand is dead.",
      "C": "C exposed one card, not his entire hand. He can continue to play but is subject to penalty. If he had exposed all his cards the hand would be dead.",
      "D": "C has exposed a card and must play with that handicap. He can call raise or fold and may be subject to penalty.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 23,
    question: "若玩家還有活著的手牌,必須留在桌邊。",
    questionEn: "A player must remain at the table if he or she has a live hand",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 24,
    question: "對於「單付者底注與盲注系統(single-payer ante and blind systems)」,TDA 的建議為何?選最完整的答案。",
    questionEn: "What is the TDA Recommendation for single-payer ante and blind systems? Pick the most complete answer.",
    options: {
      "A": "若採用單付者底注,推薦採用大盲底注(BBA)格式,且以「大盲先扣」方式計算。",
      "B": "大盲底注優於按鈕底注(Button Ante)。",
      "C": "傳統底注盲注系統較佳,因為單付者系統容易造成桌上混淆並增加計算錯誤風險。",
      "D": "必須採用「大盲底注 + 底注先扣」的計算方式。",
      "E": "推薦採用「按鈕底注 + 底注先扣」的計算方式。",
    },
    optionsEn: {
      "A": "IF a single-payer ante is used, the big blind ante format (BBA) with big-blind-first calculation is recommended",
      "B": "BB ante is preferable to Button Ante",
      "C": "The conventional ante and blind system is preferred because single-payer systems create confusion at the table and increase the risk that mis-calculations will occur",
      "D": "The BB ante with ante-first calculation is required",
      "E": "Button Ante with ante-first calculation is recommended",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 25,
    question: "玩家 A 剛報名比賽,但發現自己這手會是大盲,於是跑去咖啡廳買飲料。玩家 B 從拆桌移過來,但故意不立刻坐下,以避免付下一個大盲。這兩種情況應如何處理?",
    questionEn: "Player A recently bought into the tournament but notices his seat will have the big blind so he goes to the cafe to get a soda. Player B is moving from a broken table but does not immediately sit at the new table in order to avoid paying the next BB. How should these situations be handled?",
    options: {
      "A": "凡是躲避盲注的玩家必須受罰,處罰程度由 TD 決定。",
      "B": "初犯不予處罰。",
      "C": "躲盲注屬於自動取消資格、沒收入場費的情況。",
      "D": "躲盲注的處罰僅在玩家已就座並開始參賽後才適用。本題中只有 B 該受罰。",
    },
    optionsEn: {
      "A": "Players who dodge any blind must receive a penalty to be determined by the TD.",
      "B": "For first offense a penalty is not given.",
      "C": "Dodging a blind is a condition of automatic disqualification and forfeit of the player's buy-in.",
      "D": "Penalties for blind-dodging only start once a player has taken a seat and actually started play in the tournament. Only Player B is subject to penalty in this case.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 26,
    question: "攤牌時,牌的大小如何決定?",
    questionEn: "How is the value of the hands determined at showdown?",
    options: {
      "A": "「Cards speak for themselves」——牌自己會說話,玩家對牌型大小的宣告不具約束力。",
      "B": "每名玩家必須翻開所有牌並口頭宣告牌型,「一手一玩家」原則生效,宣告具約束力。",
      "C": "對自己牌型不確定的玩家可不發一語翻開幾張讓荷官判讀。但若玩家宣告了牌型,該宣告具約束力。",
      "D": "每名玩家必須先口頭宣告牌型,然後只翻開構成所宣告牌型的那幾張牌。",
    },
    optionsEn: {
      "A": "Cards speak for themselves. Declarations as to the value of a hand are not binding.",
      "B": "Each player must turn over all his cards and verbally declare the value of his or her hand. One player to a hand is in effect and the declaration is binding.",
      "C": "A player who is not sure of his or her hand may turn over one or more cards silently and allow the dealer to read the hand. However, if the player declares a hand value it is binding.",
      "D": "Each player must verbally declare the value of his hand then must turn over only the card(s) he holds that make the declared hand.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 27,
    question: "賽事允許前 2 小時內重新買入(re-buy)。在重買期內某玩家輸光籌碼,要求重買。籌碼送到桌上需要幾分鐘。等待期間應該如何處理?",
    questionEn: "A tournament allows re-buys for the first 2 hours. A player busts out during the re-buy period and asks for a rebuy. It takes a few minutes for chips to arrive at the table. While the player is waiting for chips what is the correct procedure?",
    options: {
      "A": "下一手仍發牌給該玩家。荷官先預支一小部分重買籌碼,在重買籌碼送達前,該玩家的賭注就以這預支部分為上限。",
      "B": "下一手仍發牌給該玩家,他以「後備籌碼(chips behind)」方式參與,上限為完整的重買金額。",
      "C": "該玩家應離開桌子去櫃台買重買,然後被分配新座位。",
      "D": "在重買籌碼送達前的所有手牌,該玩家都必須停玩。",
    },
    optionsEn: {
      "A": "Deal the player in next hand. The dealer advances the player a small portion of the re-buy. The partial advance is the total stakes the player has until the re-buy chips arrive.",
      "B": "The player is dealt in the next hand and plays chips behind up to the full amount of the re-buy.",
      "C": "The player should leave the table and go to the cashier where he will be sold the re-buy and assigned a new seat at the tournament.",
      "D": "The player must sit out any hands dealt before the re-buy chips arrive at the table.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 28,
    question: "精彩牌局正在進行。轉牌時 A 有同花順雙頭聽,B 三條。A 下注、B 加注剛好讓 A 跟注就全下。A 不情願地棄牌,接著要求看河牌,看自己的同花順會不會中。應如何處理?",
    questionEn: "An exciting hand is underway. On the turn, Player A has 4 cards to an open-end straight flush and B has trips. A bets and B raises enough to put A all-in to call. A reluctantly mucks his cards and asks to see the river to see if his straight flush would have come. What should happen?",
    options: {
      "A": "這種要求稱為「獵兔(rabbit hunting)」,TDA 規則不允許。",
      "B": "A 想知道是否會中同花順可以理解,但這項要求必須由 TD 核准或拒絕,荷官應通知 TD。",
      "C": "荷官可偶爾基於禮貌答應這項要求(不得濫用),不需經 TD 核准。",
      "D": "正確禮儀是若有人要求,只能展示河牌。A 要求的就是河牌,所以應該批准。",
    },
    optionsEn: {
      "A": "This request is called \"rabbit hunting\" and is not allowed under Poker TDA rules.",
      "B": "Player A understandably wants to know if he would have hit his straight flush, but the TD must approve or deny this request. Dealer should call the TD.",
      "C": "The dealer may occasionally grant this request as a courtesy not to be abused and does not need to ask for TD approval.",
      "D": "Proper etiquette is that only the river card must be shown on request. Since A has asked to see a river card this request should be granted.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 29,
    question: "在奧馬哈高低牌(Omaha hi-low 8 or better)中,Seat 5 為按鈕。Seat 2 贏低牌,Seat 4 贏高牌。底池盡可能平分後剩下一個奇數籌碼(odd chip)。應歸誰?",
    questionEn: "In Omaha hi-low 8 or better, Seat 5 is the button. Seat 2 wins the low and Seat 4 wins high. The pot is divided as evenly as possible and one odd chip remains. What player, if any, gets this chip?",
    options: {
      "A": "底池絕不應該不平均分配。該籌碼留到下一手底池。",
      "B": "Seat 2 拿,因為他是 Button 左邊第一位玩家。",
      "C": "Seat 2 與 Seat 4 應抽牌決定誰拿奇數籌碼。",
      "D": "Seat 4 拿,因為他贏的是高牌。",
    },
    optionsEn: {
      "A": "No pot should ever be divided unevenly. The chip becomes part of the pot for the next hand.",
      "B": "Seat 2 should get the chip because he is the first player to the left of the button.",
      "C": "Seat 2 and Seat 4 should draw a card randomly for the odd chip.",
      "D": "Seat 4 should get the chip because he had the high hand.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 30,
    question: "綜合賽事(mixed-game)目前換到 7 張 Stud。起手發牌時,荷官不慎把 Seat 6 的第二張底牌正面朝上發出。應如何處理?",
    questionEn: "In a mixed-game event the current game has just switched to 7-stud. On the initial deal, the dealer accidentally deals the 2nd downcard face-up to Seat 6 and the floor is called. How should this be handled?",
    options: {
      "A": "TDA 規則規定,Stud 中若有玩家的前兩張底牌被荷官露出,就是誤發牌,因為露牌可能改變誰是最小牌(low-card)、也就是 bring-in 的決定。",
      "B": "即使有一張底牌對全桌曝光,起手發牌仍照常進行。Seat 6 的第三張會發為底牌(face-down)。",
      "C": "TDA 規則規定,Stud 中若有玩家的前兩張底牌因荷官失誤露出,屬於誤發牌,因為這擾亂了哪些牌應該對他人公開、哪些應該隱藏的原始順序。",
      "D": "TDA 規則規定,Stud 中若有玩家的前兩張底牌因荷官失誤露出,屬於誤發牌,因為剩餘牌堆(stub)的完整性受到質疑。",
    },
    optionsEn: {
      "A": "TDA Rules require that in stud, if any player's first 2 downcards are exposed by dealer it is a misdeal because dealing face-up may change which player has the low-card and must therefore be the bring-in.",
      "B": "The initial deal should proceed despite exposure of a downcard to the entire table. Seat 6 will receive her 3rd card face-down.",
      "C": "TDA Rules require that in stud, if any player's first 2 downcards are exposed by dealer error it is a misdeal because dealing face-up disturbs the original order of which cards are exposed to other players and which are hidden.",
      "D": "TDA Rules require that in stud, if any player's first 2 downcards are exposed by dealer error it is a misdeal because the integrity of the stub is in question.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 31,
    question: "玩家必須自行保護手牌。若玩家在牌上放了清楚可見的籌碼保護物,而荷官仍誤把牌收走,該玩家有權拿回所有下注。",
    questionEn: "Players must protect their own hands. If a player keeps a clearly visible card protector on his cards and the dealer mucks them accidentally the player is entitled to a return of all his bets on that hand.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 32,
    question: "翻牌後,小盲(A)開注 1,000,輪到 B 行動。在 B 行動前,C 把牌往前丟出做出棄牌動作並說「我棄牌,我跟不起 10,000」。C 明顯誤解了下注金額而提前棄牌。應如何處理?",
    questionEn: "Post-flop, the SB (Player A) opens for 1,000 and action is on B. Before B can act, C tosses his cards in a muck gesture saying \"I fold, I can't call 10,000\". C clearly misunderstood the bet amount and folded out of turn. What should happen?",
    options: {
      "A": "行動退回 B,B 可跟注、加注、棄牌。因為嚴重誤解導致 C 原本棄牌,輪到 C 時只能跟或棄,失去加注權利。",
      "B": "行動退回 B,B 可跟注、加注、棄牌。不論 B 怎麼做,C 越序棄牌仍具約束力,其手牌作廢。",
      "C": "行動退回 B。若 B 只跟注 A 沒改變行動,C 必須棄牌。若 B 加注改變了行動,則 C 解除越序棄牌的約束,可自由行動。",
      "D": "行動退回 B,B 可跟注、加注、棄牌。然後輪到 C,因為他原本是嚴重誤解下注金額才棄牌,所以他可以自由選擇任何行動。",
    },
    optionsEn: {
      "A": "Action backs up to B who can call, raise, or fold. Action is then on C because a gross misunderstanding led to his initial fold. C can only smooth call or fold, he has lost his right to raise.",
      "B": "Action backs up to Player B who can call raise or fold. Regardless of B's action, C's out of turn fold is binding. His hand is dead and will be mucked.",
      "C": "Action backs up to B. If B calls A then action hasn't changed to C and C must fold. If B changes action by raising then C is released from his out-of-turn fold and may take any action he wants.",
      "D": "Action backs up to B who can call, raise, or fold. Action is then on C who can take any action he wants because a gross misunderstanding of the bet led to his initial gesture to fold.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 33,
    question: "Mary 喜歡在桌邊偶爾查看自己做的下注賠率表和撲克策略表。下列哪個答案最完整地說明 TDA 對此的規則?",
    questionEn: "While at the table, Mary likes to occasionally refer to a chart she's made about betting odds and other poker strategy. What answer most completely explains TDA rules on this issue.",
    options: {
      "A": "桌上禁止使用下注圖表與 App。",
      "B": "任何尚在牌中的玩家在面對行動時可使用下注圖表與 App。",
      "C": "任何尚在牌中的玩家皆可使用下注圖表與 App。",
      "D": "只有不在本手牌中的玩家才可在桌邊使用下注圖表與 App。",
    },
    optionsEn: {
      "A": "Betting charts and apps may not be used at the table",
      "B": "Betting charts and apps may be used by any player in the hand but only if they are currently facing action.",
      "C": "Betting charts and apps may be used by any player currently involved in the hand.",
      "D": "Betting charts and apps may only be used at the table by players not involved in the current hand",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 34,
    question: "在 Stud 牌中,A 下注 1000,輪到 B 行動。B 思考一陣後拿起自己的明牌(upcards)。在 Stud 中這是有約束力的棄牌動作,手牌作廢。",
    questionEn: "In stud Player A bets 1000 and the action is on B. B thinks awhile then picks up his upcards. This is a binding gesture to fold in stud, the hand is dead.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 35,
    question: "賽事剩 3 名玩家。A 是 Button,B 是小盲,C 是大盲。B 被淘汰,賽事剩 2 名玩家。下一手的 Button 與盲注應如何安排?",
    questionEn: "3 players remain in the tournament. A is the button, B is the SB, C is the BB. B busts out, leaving 2 players in the tournament. How should buttons & blinds be arranged in the next hand?",
    options: {
      "A": "C 是小盲(因為他上一手是大盲)。在單挑(heads up)中,小盲就是 Button,所以 C 也是 Button。",
      "B": "A 上一手是 Button,Button 必須移到下一位剩餘玩家(即 C)。A 在 Button 左邊,所以是小盲。",
      "C": "賽事從 3 人變 2 人單挑時,TDA 規則要求玩家抽牌決定位置與盲注。",
      "D": "Button 必須移動,沒有人能連續兩手都是 Button。A 上一手是 Button,所以這一手是 C。盲注由抽牌決定。",
    },
    optionsEn: {
      "A": "The SB is on C because he had the BB last hand. The button is on C because the SB has the button heads up.",
      "B": "Player A had the button last hand. The button must move to the next remaining player, C in this case. The SB is on A because he is to the left of the button.",
      "C": "When the tournament moves from 3 players to two players heads up, TDA rules require that the players must draw for position and blinds.",
      "D": "The button must move because no player can have the button twice in a row. A had the button last so C must have the button this hand. Players will draw for the blinds.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 36,
    question: "賽事為德州撲克,盲注 1000/2000。4 名玩家進入轉牌:A 開注 6,000,B 加注至總額 20,000。C 推出 6,000。應如何處理?",
    questionEn: "The game is Texas Holdem, blinds are currently at 1000 / 2000. Four players remain for the turn: Player A opens for 6,000 and Player B raises to 20,000 total. Player C pushes out 6,000. How should this be handled?",
    options: {
      "A": "C 屬於跟注不足(undercall),6,000 留在底池。叫 TD 來決定 C 是否必須補足 14,000,或者可以讓 6,000 留在底池後棄牌。",
      "B": "這是「嚴重誤解」,因為短缺金額(14,000)大於下注金額(6,000)。C 可選擇跟足 20,000 或拿回 6,000 後棄牌。",
      "C": "C 推出籌碼即為跟注動作,必須把下注補到總額 20,000。",
      "D": "C 跟注不足,可選擇把 6,000 留在底池後棄牌,或補足 20,000。",
    },
    optionsEn: {
      "A": "Player C has undercalled. The 6,000 must be left in the pot. The TD will be called to determine whether Player C will be obligated for the remainder of 14,000 or be allowed to leave the 6,000 in and fold.",
      "B": "This is a \"gross misunderstanding\" because the short amount (14000) exceeds the bet amount (6000). Player C has the option to either make the full call of 20,000, or retrieve his 6,000 bet and fold.",
      "C": "Player C has made a \"call\" gesture by pushing out chips. He must increase his bet to a total of 20,000.",
      "D": "Player C has undercalled and it is now C's choice whether to leave the 6,000 in and fold, or call the full 20,000.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 37,
    question: "無限注德州撲克,盲注 100/200,牌局 3 名玩家。翻牌後 A 開注 1000。B(籌碼 20k)不發一語推出兩個 500 與四個 100。C 不發一語推出自己最後的籌碼:兩個 500 與四個 100。已發生什麼行動?",
    questionEn: "NLHE 100/200 blinds. 3 players remain in the hand. Post-flop player A opens for 1000. Player B (with 20k chip stack) silently pushes out two 500 chips and four 100 chips. Player C silently pushes out his last chips: two 500's and four 100's. What action has taken place?",
    options: {
      "A": "兩位玩家都表現出加注意圖:推出超過下注額的籌碼,且帶有非跟注必需的 4 個 100。基於加注意圖,B 加注至 2000,C 全下總額 1400。A 還需補 1000 跟注,加注權保留。",
      "B": "B 不發一語推出不到最小加注 50%,視為跟注。C 全下 1400。A 是原下注者(1000),可再補 400 跟注或加注至至少 2400。若 A 沒加注,B 也只能補 400 跟。",
      "C": "下注 1000,最小加注 1000。B 與 C 都推出小於最小加注 50% 的籌碼,兩人都沒宣告加注,所以都是跟注,各退回 400。",
      "D": "B 不發一語推出不到最小加注 50%,視為跟注。C 全下 1400。A 與 B 可各補 400 跟注或棄牌,不可加注。",
    },
    optionsEn: {
      "A": "Both players indicate intent to raise by pushing out more than the bet amount AND pushing out chips not needed to call (the four 100's). Because of intent to raise, B has raised to 2000 total and C is all-in for 1400 total. It is 1000 more to A to call, with raises open.",
      "B": "B has called because he pushed out less than 50% of a min raise silently. C is all-in for 1400. Because he was the original bettor of 1000, A may call the 400 more or raise to at least 2400 total. If A does not raise, B can only call the 400 more.",
      "C": "The bet is 1000 and a minimum raise is 1000. Both B and C have pushed out multiple chips totaling less than 50% of a minimum raise. Because neither player declared raise, both B and C have called and will each receive 400 back.",
      "D": "B has called because he pushed out less than 50% of a min raise silently. C is all-in for 1400. A and B may each call the 400 more or fold, they cannot raise.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 38,
    question: "HORSE 賽事同時有 Stud 與翻牌類遊戲。目前 Omaha 那手 Button 在 Seat 6,下一手換成 Razz(7-stud low)。換到 Razz 時 Button 應放哪裡?Razz 期間若需要平衡桌數應移動哪位玩家?",
    questionEn: "A HORSE event has both stud and board games. For the current Omaha hand the button is on seat 6. On the next hand the game changes to Razz (7-stud low). On the change to Razz, where is the button placed and during Razz what player if any should be moved to balance another table?",
    options: {
      "A": "Button 留在 Seat 6。移動的玩家:新桌的空座距其 Button 左邊幾個座位,就從本桌 Button 左邊相同位置的玩家移動。",
      "B": "Razz 期間 Button 不在桌上,要移動的玩家以抽牌決定。",
      "C": "Button 移到 Seat 7,並在 Razz 期間保持不動。要移動的玩家是移動時 Seat 7 左邊第 2 位(若是德州撲克則為大盲位)。",
      "D": "Button 留在 Seat 6。第一手要移的是 Seat 7,每打一手 Razz 往前推一個座位。",
    },
    optionsEn: {
      "A": "The button stays on seat 6. The player to move is the player exactly as many seats to the left of the button as the open seat at the new table is to the left of the button on that table.",
      "B": "The button is off the table during Razz. A player to be moved is chosen by random card draw.",
      "C": "The button moves to seat 7 and stays there during Razz. A player to be moved is the 2nd player to the left of seat 7 at the time of the move (i.e. the player who would be BB if the game was holdem).",
      "D": "The button remains on seat 6. The player to be moved if during the 1st hand is seat 7. This advances one seat for each hand of Razz that is played.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 39,
    question: "XYZ 賭場的翻牌類賽事(如德州撲克、奧馬哈)通常每桌坐 9 人。XYZ 翻牌類賽事的決賽桌應該坐幾人?",
    questionEn: "XYZ Casino normally seats 9 players at it's flop game tournaments such as Texas Holdem and Omaha. How many players should sit at the final table of XYZ's flop game tournaments?",
    options: {
      "A": "賽事剩 10 人時組成決賽桌。",
      "B": "TDA 建議賽事剩 9 人時組成決賽桌。",
      "C": "與起始桌平均人數相同。",
      "D": "與起始桌中人數最多的那一桌相同。",
    },
    optionsEn: {
      "A": "The final table should form when the tournament has 10 players remaining.",
      "B": "The TDA recommends the final table should form when the tournament has 9 players remaining.",
      "C": "The same number of players as the average-size starting table.",
      "D": "The same number of players as the starting table with the largest number of players.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 40,
    question: "賽事進入最後幾桌時,為維持公平性,TDA 建議當該桌人數比滿桌少不到 2 人時,應減少底注(ante)。",
    questionEn: "As the tournament reaches the final few tables, in order to maintain fairness the TDA recommends that the ante be reduced if the number of players at the table is less than 2 players short of a full table",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 41,
    question: "玩家 A 換桌時,以某種方式攜帶籌碼,使籌碼一度離開視線。應如何處理?",
    questionEn: "While moving to a new table, Player A transports his chips in a manner that takes them out of view. How should this be handled?",
    options: {
      "A": "進行籌碼點數。若全部都在,A 帶全部籌碼繼續參賽,但可能受罰。若有缺,則 A 取消資格,籌碼移出賽事。",
      "B": "自動取消資格。A 退出賽事,籌碼移出賽事。",
      "C": "離開視線的籌碼沒收且移出賽事。A 是否取消資格由 TD 決定。",
    },
    optionsEn: {
      "A": "A chip count is done. If all chips are present, A continues in the event with all chips but may face penalty. If chips are missing, A is disqualified and chips are removed from play.",
      "B": "This is automatic disqualification. A is out of the event and the chips are removed from play.",
      "C": "The hidden chips are forfeited and out of play. Player A may be disqualified at TD's option.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 42,
    question: "德州撲克,A 持 Ah-Ad,B 持 Qs-Ks。公共牌 6d-Ac-10d-Jd-3d。攤牌時 B 亮出 Qs-Kc(最大順子)。A 接著清楚地把兩張紅 A 露給所有人看並說「比我的三條 A 大」,然後把兩張紅 A 正面朝下丟入棄牌堆。底池歸誰?為什麼?",
    questionEn: "In Texas Holdem, Player A holds Ah-Ad and B holds Qs-Ks. The board is 6d-Ac-10d-Jd-3d. At showdown B tables Qs-Kc for top straight. Player A then clearly exposes two red Aces for all to see saying \"beats my trip Aces\" then throws the two red aces onto the muck face down. Who wins the pot and why?",
    options: {
      "A": "玩家必須保護自己的手牌,這是撲克基本原則。只有 B 的牌仍亮出未進棄牌堆,他必須贏得底池。",
      "B": "即便 A 亮出來的牌可能會贏,他已明確宣告為三條 A,具不可撤回的約束力。底池判給 B。",
      "C": "A 清楚亮出完整的牌(同花 A 高方塊同花)。雖然他誤判並棄牌,但攤牌時亮出的贏牌不能被作廢。底池判給 A。",
      "D": "荷官應尊重 A 在攤牌時的棄牌權利,把底池判給仍有亮牌的 B。",
    },
    optionsEn: {
      "A": "Players must protect their hands; this is a cardinal rule of poker. Only B's hand remains exposed and un-mucked and he must receive the pot.",
      "B": "Even if Player A showed a hand that could have won, A irrevocably declared his hand to be trip Aces and this is binding. Award pot to B.",
      "C": "Player A showed the winning hand (Ace high diamond flush). Although he misread the hand and then mucked it, we cannot kill a winning hand that was tabled at showdown. Award the pot to A.",
      "D": "Dealer should respect A's right to muck at showdown and award the pot to Player B who has the remaining exposed hand.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 43,
    question: "玩家必須在自己座位上才能要求計時(call for clock)。",
    questionEn: "A player must be at his seat in order to call for a clock",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 44,
    question: "下列哪個答案最完整地反映 TDA 對玩家如何維持籌碼堆放的建議?",
    questionEn: "What answer most completely reflects the TDA recommendation for how players should maintain their chip stacks?",
    options: {
      "A": "玩家有權合理數對手籌碼。籌碼可以任何方式堆放,只要能讓人合理數清楚。",
      "B": "所有高面額籌碼都應放在前排清楚可見的位置。",
      "C": "整齊分堆、每堆 20 個倍數,高面額堆放在前排最清楚可見的位置。",
      "D": "每個面額分開整齊堆放,高面額必須放在前排最清楚可見的位置。",
    },
    optionsEn: {
      "A": "Players are entitled to a reasonable count of opponents stacks. Players may stack chips in any manner as long as it permits reasonable counting of the chips.",
      "B": "All higher denomination chips should be in plain view among the front stacks.",
      "C": "Clean separate stacks in multiples of 20 with higher denomination stacks in front in plainest view.",
      "D": "Clean separate stacks for each denomination. Higher denomination stacks must be at the front in plainest view.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 45,
    question: "下列哪一答案最完整地描述 TDA 對桌上使用電子與通訊設備的政策?",
    questionEn: "What answer most completely describes TDA policy regarding the use of electronic and communication devices at the table?",
    options: {
      "A": "這類裝置不可造成困擾、延遲或競爭優勢,且持有活著手牌的玩家不可使用。",
      "B": "桌上任何玩家任何時候都不可使用此類裝置。",
      "C": "尚在牌中的玩家可使用,但輪到自己行動時不可互動。",
    },
    optionsEn: {
      "A": "Such devices must not create a nuisance, delay, or competitive advantage and players with live hands may not interact with such devices.",
      "B": "No such devices may be used by any player at the table at any time.",
      "C": "Players currently in the hand may use such device but may not interact with it when the action is on them.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 46,
    question: "下列哪些違規必須處罰?(複選)額外選項:E. 消極對局(Soft play)F. 躲盲注(Dodging a blind)G. 作弊(Cheating)",
    questionEn: "For which of the following infractions must a penalty be invoked? Select all that apply, if any: Additional visible options: E. Soft play F. Dodging a blind G. Cheating",
    options: {
      "A": "丟牌",
      "B": "在行動未完成時露牌",
      "C": "違反「獨立完成手牌」原則",
      "D": "辱罵或干擾性行為",
      "E": "消極對局(soft play)",
      "F": "躲避盲注",
      "G": "作弊",
    },
    optionsEn: {
      "A": "Throwing a card",
      "B": "Exposing a card while action is pending",
      "C": "Violating one-player-to-a-hand",
      "D": "Abusive or disruptive behavior",
      "E": "Soft play",
      "F": "Dodging a blind",
      "G": "Cheating",
    },
    answer: "ABCDEFG",
    multiSelect: true,
  },
  {
    id: 47,
    question: "Jim 擁有一間機車安全帽公司,想戴自家新型先進安全帽,該安全帽附深色遮陽鏡片覆蓋整張臉,且上面有多個貼紙,賽事還會電視轉播。應如何處理?",
    questionEn: "Jim owns a motorcycle helmet company and wants to wear their new advanced helmet with dark protective visor that covers and protects the entire face. The helmet also has several decals and the game will be televised. How should this be handled?",
    options: {
      "A": "玩家應隨時可被辨識。若安全帽妨礙辨識或干擾其他玩家,可被要求摘下。貼紙由場館與電視台政策決定。",
      "B": "TDA 規定凡穿戴可辨識商業 logo 者,需與場館簽訂書面協議。",
      "C": "不需處理,玩家本來就會穿戴各種東西,不是場館的責任。",
    },
    optionsEn: {
      "A": "Players should be identifiable at all times and may be asked to remove the helmet if it inhibits identification or distracts other players. The decals are up to house and network policy",
      "B": "The TDA requires a written agreement between the house and any player who is wearing a commercially identifiable logo.",
      "C": "No action is required, players wear a wide range of items and it's not the house's responsibility.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 48,
    question: "限注奧馬哈剩 4 名玩家。盲注 1000/2000。翻牌後 A 開注 2000。B 在思考時,C 說「如果你跟我就加注」。應如何進行?",
    questionEn: "Four players remain in limit Omaha. Blinds are 1000/2000. Postflop Player A opens for 2000. B is thinking when C says \"if you call I will raise\". How should action proceed?",
    options: {
      "A": "C 做出條件性下注聲明,依 Rule 1 由 TD 裁量是否具約束力。TD 也應警告或處罰 C。",
      "B": "牌局中的口頭聲明應按字面解讀。C 只承諾在 B 跟注時加注。若 B 棄牌或加注,C 可自由選擇。",
      "C": "若 B 跟注則 C 必須加注。TD 應警告或處罰 C 的越序干擾行為。",
      "D": "C 的條件性聲明屬於不具約束力的嘴砲。TD 應警告或處罰 C,並建議 B 忽略該言論。",
    },
    optionsEn: {
      "A": "C has made a conditional betting statement that may be binding at TD's discretion under Rule 1. Also, the TD should warn or penalize C.",
      "B": "Verbal statements during a hand must be interpreted literally. C has committed to a raise only if B calls. If B folds or raises then C has all options open.",
      "C": "If B calls then C must raise. The TD should warn or penalize C for disruptive out-of-turn behavior.",
      "D": "C made a conditional statement that is non-binding trashtalk. The TD should warn or penalize C and advise B to ignore the statement.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 49,
    question: "賽事為無限注德州撲克,盲注 100/200。轉牌時 A 口頭宣告一個不清楚的下注金額:「I'll make it eight」。A 的行動應如何解釋?額外選項:E. 不清楚的下注應以較低金額判定,具約束力下注 800。",
    questionEn: "Game is NLHE, 100/200 blinds. On the turn Player A verbally declares an unclear bet (\"I'll make it eight\"). How should A's action be interpreted? Additional visible options: E. Unclear bets should be ruled as the lower amount. It's a binding bet of 800.",
    options: {
      "A": "不清楚的下注視同沒說。A 可下注任何合法金額或棄牌。",
      "B": "不清楚的下注應以較高金額判定,具約束力下注 8000。",
      "C": "若 A 下注前底池有 8000 以上,則為下注 8000;若少於 8000,則為下注 800。",
      "D": "金額不清楚,但下注意圖明確。A 可下注任何合法金額,但不能棄牌。",
      "E": "不清楚的下注應以較低金額判定,具約束力下注 800。",
    },
    optionsEn: {
      "A": "Unclear bets are treated as if nothing was said. Player A can bet any legal amount or fold.",
      "B": "Unclear bets should be ruled as the higher amount. It's a binding bet of 8000.",
      "C": "If there is 8000 or more in the pot before A's bet, it is a bet of 8000. If less than 8000 it's a bet of 800.",
      "D": "The amount is unclear but the intention to bet is certain. Player A can bet any legal amount but cannot fold.",
      "E": "Unclear bets should be ruled as the lower amount. It's a binding bet of 800.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 50,
    question: "某玩家多次拿到第二大牌,剛剛又在大底池被河牌逆轉。該玩家可以要求換牌。",
    questionEn: "A player has the second-best hand several times and has just been rivered out of a large pot. This player may request a change of the deck.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 51,
    question: "賽事為無限注德州撲克,桌上 8 人。荷官開始發新一手的起手底牌,輪到 Seat 5 時,該座玩家不在位子上。應如何處理?",
    questionEn: "Game is NLHE, 8 players. A dealer deals the initial downcard on a new deal and when seat 5 is reached the player is not at the seat. What should happen?",
    options: {
      "A": "繼續發牌到該座位。若該玩家在全桌最後一張起手底牌發出前回到座位,手牌算活的。",
      "B": "繼續發牌到該座位,若發到 Seat 5 最後一張時人還沒回來,則手牌作廢。",
      "C": "兩張底牌都發到該座位。但因為玩家第一張發牌時不在座位上,起手發完全桌後手牌作廢。",
      "D": "起手底牌照發到該座位,然後叫 TD,TD 依 Rule 1 為賽局最佳利益裁決。",
    },
    optionsEn: {
      "A": "Deal all initial downcards to the seat. If the player returns to their seat before the last initial downcard is dealt to all players at the table, the hand is live.",
      "B": "Deal to the seat, and if the player is not at the seat by the time the last initial card is dealt to seat 5, then kill the hand.",
      "C": "Deal both downcards to the seat. However, because the player wasn't \"at his seat\" for the first initial card, the hand should be killed after the initial deal to all players.",
      "D": "Deal all initial downcards to the seat. Then call the TD who will make a Rule 1 ruling in the best interest of the game.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 52,
    question: "3 名玩家進入攤牌。A 是詐唬,立即把牌正面朝下棄掉。B 忘記 C 還在牌中,以為自己贏了也把牌正面朝下棄掉。荷官把 A、B 的牌埋進棄牌堆。此時 C 說「嘿,我還有一手牌」。底池應如何分配?",
    questionEn: "Three players make it to the showdown. Player A was on a bluff and immediately mucks her cards face down. Player B forgets Player C is still in the hand and Player B also mucks his cards face down, thinking he has won. The dealer buries A and B's cards in the muck. Player C then announces \"hey I have a hand\". How should this pot be awarded?",
    options: {
      "A": "基於公平,底池三人均分。",
      "B": "C 是唯一還活著的手牌,獨得全部底池。",
      "C": "C 沒在 B 棄牌前出聲,所以底池歸 B。",
      "D": "A 的棄牌動作明顯誤導 B 棄牌。底池由 B 與 C 均分,A 因有過失而一無所得。",
    },
    optionsEn: {
      "A": "Fairness dictates that the pot be split three ways.",
      "B": "Player C has the last surviving live hand and will receive the entire pot.",
      "C": "Player C did not speak up before Player B mucked his cards. Therefore Player B is entitled to the entire pot.",
      "D": "Player A's mucking action clearly caused B to make a mistake and muck his cards. The pot should be split between Player B and C, but A is at fault and will receive nothing.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 53,
    question: "7 張 Stud,起手發第一張底牌給全桌後,荷官在發第二張底牌時把 Seat 4 的牌甩到他的籌碼堆上,牌翻過來露出黑桃 10。應如何處理?",
    questionEn: "In 7-card stud on the initial deal the 1st downcard is dealt to all players. While dealing the 2nd downcard, the dealer tosses the card for Seat 4 in a manner that hits 4's chip stack and flips over revealing the 10 of spades. How should this be handled?",
    options: {
      "A": "Seat 4 手牌作廢。因屬荷官失誤,退回底注。下一手再給他發牌。",
      "B": "黑桃 10 作為 Seat 4 的起手明牌。發 3rd street 起手明牌時,荷官把 Seat 4 的牌發成底牌。",
      "C": "黑桃 10 作為 4th street 的燒牌。繼續發完所有人第二張底牌,再發明牌,最後 Seat 4 的第二張底牌用「原本要當 4th street 燒牌」的那張。",
      "D": "在 Stud 中這是誤發牌。荷官應收回所有牌、重新混牌、重洗、重發。",
    },
    optionsEn: {
      "A": "Seat 4 has a dead hand. His ante is returned because of dealer error. Deal him in next hand.",
      "B": "The 10 of spades will be Seat 4's initial upcard. When dealing the initial upcard on 3rd street the dealer will deal the card to Seat 4 face down.",
      "C": "The 10 of spades will be the 4th street burn card. Continue dealing the 2nd downcard to everyone, then each player gets their upcard then Seat 4 gets his 2nd downcard at the end (his downcard is the card that would have been the burn for 4th street).",
      "D": "This is a misdeal in stud games. The dealer should recover all cards, remix, reshuffle and start the deal over.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 54,
    question: "TDA 規則採用哪一種 Button 規則?",
    questionEn: "Which button rule is used under TDA rules?",
    options: {
      "A": "TDA 規則交由各場館自行決定。",
      "B": "移動 Button 規則(moving button)。",
      "C": "死 Button 規則(dead button)。",
    },
    optionsEn: {
      "A": "TDA Rules leave this to house policy.",
      "B": "The moving button rule.",
      "C": "The dead button rule.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 55,
    question: "下列哪個答案最完整地說明 TDA 對「桌上講手機」的規則?",
    questionEn: "What answer most completely describes the TDA rule for talking on a cell phone?",
    options: {
      "A": "只有不在當前牌局中的玩家才可在桌邊講手機。",
      "B": "桌上任何玩家只要不干擾他人都可講手機。",
      "C": "桌上任何玩家都不可講手機。",
    },
    optionsEn: {
      "A": "Only players who are not involved in the current hand may talk on the phone at the table",
      "B": "All players at the table may talk on their phone as long as the conversation is not distracting to other players",
      "C": "No player may talk on a phone while at the table.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 56,
    question: "底池限注奧馬哈 8 或更好(PLO 8)中,最大加注次數是多少?額外選項:E. 每位玩家有一次加注機會,允許的總加注次數視桌上人數(扣除受罰中的玩家)而定。",
    questionEn: "What is the maximum number of raises in Pot Limit Omaha 8 or better? Additional visible options: E. Every player gets one chance to raise. The total raises allowed depends on the number of players at the table less any players on penalty.",
    options: {
      "A": "起始下注加 3 次加注。",
      "B": "TDA 沒有最大加注次數規則,適用場館規定。",
      "C": "牌中超過 2 人時為起始下注加 3 次加注。若只剩 2 人單挑,則取消 3 次上限,加注次數不限。",
      "D": "底池限注與無限注皆無最大加注次數限制。",
      "E": "每位玩家有一次加注機會,總加注次數視桌上人數(扣除受罰者)而定。",
    },
    optionsEn: {
      "A": "The initial bet plus 3 raises.",
      "B": "The TDA does not have a rule on maximum raises, the house limit applies.",
      "C": "The initial bet plus 3 raises if more than 2 players are in the hand. If players fold and only 2 remain, the maximum of 3 raises is waived and any number is allowed.",
      "D": "There is no maximum number of raises in pot-limit and no-limit play.",
      "E": "Every player gets one chance to raise. The total raises allowed depends on the number of players at the table less any players on penalty.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 57,
    question: "翻牌後 A 應先行動,但 B 越位下注 5000。TD 把行動退回給正確的 A。若 A 改變了行動(改為下注而非過牌),則 B 從越序下注中解除,可自由選擇:跟注、加注或棄牌。",
    questionEn: "Player A is first to act post-flop but B bets 5000 out of turn. The TD backs the action up to the rightful player (A). If A changes the action by betting instead of checking, B is released from his out-of-turn bet and may take any action he wants: call, raise, or fold.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 58,
    question: "從拆桌(broken table)被移到別桌的玩家,可坐在小盲位置(並付小盲)。",
    questionEn: "Players moving from a table that was broken (closed) in order to fill seats at other tables may sit at the small blind position (and post the SB) at the table they are moved to.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 59,
    question: "奧馬哈 H/L 賽事盲注 2000/4000,4 人進入轉牌。發出轉牌後 A 下注 30,000,B 跟注。C 想了一陣後丟出一個 1,000 籌碼。應如何處理?",
    questionEn: "In an Omaha H/L tournament the blinds are currently 2000 / 4000. 4 players are left to see the turn. After the turn is dealt Player A bets 30,000. Player B calls. Player C thinks a bit then tosses out a single 1,000 chip. How should this be handled?",
    options: {
      "A": "C 顯然誤解了下注。荷官應停止行動詢問 C 的意圖。若 C 選擇棄牌,1,000 視為輪到他時的下注沒收,留在底池。",
      "B": "相對下注額丟出極小籌碼的行為嚴重不建議,可能受罰。叫 TD 來,TD 可判定為跟注 30,000 或自行裁量。",
      "C": "C 顯然誤解下注。荷官應停止行動詢問 C 的意圖。若 C 選擇棄牌,1,000 應退回。",
      "D": "丟出在賽事中最低面額的籌碼即視為跟注。輪到下一位 D。",
    },
    optionsEn: {
      "A": "Player C has clearly mis-understood the bet. The dealer should stop the action and ask Player C what his intention is: to call or fold. If C elects to fold the 1,000 is forfeited as a bet in turn and left in the pot.",
      "B": "Tossing out a chip that is relatively tiny to the bet is strongly discouraged and may be penalized. The TD will be called and may rule this a full call of 30,000 or otherwise at his or her discretion.",
      "C": "Player C has clearly mis-understood the bet. The dealer should stop the action and ask Player C what his intention is: to call or fold. If C elects to fold the 1,000 should be returned.",
      "D": "Tossing out the lowest denomination in play always indicates a call. Move on to Player D.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 60,
    question: "賽事開始幾手後發現某玩家坐錯座位。他起始籌碼是正確的。應如何處理?",
    questionEn: "After the first few hands of a tournament, a player is found to be in the wrong seat. He started out with the correct starting chip stack. What should happen?",
    options: {
      "A": "這是嚴重違規,可能導致坐錯座位的玩家受罰或取消資格。TD 依 Rule 1 做出最公平的裁決。",
      "B": "這是場館失誤,玩家可能已習慣此桌。給玩家選擇:留在現座或回原座。",
      "C": "保持現狀,因為要把所有人調回正確座位可能要移動太多玩家。",
      "D": "把該玩家連同目前籌碼移到正確座位。若該座位上已有人,把他移到他的正確座位,以此類推。",
    },
    optionsEn: {
      "A": "This is a serious infraction that may result in penalty or disqualification of the player in the wrong seat. TD will use Rule 1 to make the fairest ruling possible.",
      "B": "This was a house error and the player may have become used to this table. Give the player the option to move to the original seat or stay where he is.",
      "C": "Leave things as they are because too many players may need to be moved in order to get the seats straightened out.",
      "D": "Move the player and his current chip stack to the correct seat. If a player is in that seat, move that player to his correct seat and so on.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 61,
    question: "德州撲克盲注 200/400。一手牌結束、底池分配完畢,小盲為下一手付了 200。荷官開始洗牌,計時系統宣告盲注升到 250/500。大盲付了 500。本手盲注應該是多少?為什麼?",
    questionEn: "In Texas Holdem blinds are 200/400. A hand finishes and the pot is awarded. SB posts 200 for the next hand. The dealer then begins shuffling. The timing system then announces blinds are 250/500. The BB posts 500. What should blinds be for this hand and why?",
    options: {
      "A": "200/400,因為荷官在下一級盲注宣布前已開始洗牌。",
      "B": "250/500,因為新級別宣布時還沒發牌。荷官必須在發第一張牌前確保盲注符合當前級別。",
      "C": "200/400,因為小盲在下一級盲注宣布前已付了 200。",
      "D": "250/500,因為大盲根據新級別宣告正確地付了 500。",
    },
    optionsEn: {
      "A": "200/400 because the dealer started riffling the cards before the next blind level was announced.",
      "B": "250/500 because no cards were dealt prior to the new level announcement. The dealer must ensure that blinds match current levels prior to dealing the first card.",
      "C": "200/400 because the SB has posted 200 prior to announcement of the next blind level.",
      "D": "250/500 because the BB has correctly posted 500 pursuant to the announcement of the new level.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 62,
    question: "德州撲克中,玩家持 Ah-Ac,公共牌 As、Kh、9h、7h、2h。攤牌時她誤宣告自己最大牌為「三條 A」。由於「獨立手牌」原則,她受此宣告約束,TD 應判她為三條 A 而非 A 高同花。",
    questionEn: "In Texas holdem, player has Ah-Ac in her hand. Board is As, Kh, 9h, 7h, 2h. At showdown, if she mistakenly declares her best hand is \"3 aces\" she is bound by that declaration because it is \"one player to a hand\". The TD should rule that she has 3 aces, not an Ace-high flush.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 63,
    question: "無限注 2-7 lowball,盲注 2000/4000。換牌後 A 開注 6000,B 跟注,C 說「raise」並推出一疊混合籌碼後放開。C 接著說「總共 15,000」。實際數完 C 推出的是 13,500。輪到 D 時面對多少下注?為什麼?",
    questionEn: "In no-limit 2-7 lowball, blinds are 2000 / 4000. After the draw Player A opens betting for 6000 and B calls. C says \"raise\", then pushes and releases a stack of mixed chips. C then says \"it's 15,000 total\". C's chips are counted and he has actually pushed out 13,500. What is the bet to Player D and why?",
    options: {
      "A": "C 先說「raise」、再推出籌碼、然後才說金額,所以下注以實際籌碼數為準。D 面對 13,500 總額。",
      "B": "C 在說金額前就說了「raise」,所以限制為最小加注。最小加注 4000(大盲額),D 面對總額 10,000。",
      "C": "C 在說金額前就說了「raise」,限制為最小加注。最小加注 6000(先前最大下注或加注額),D 面對總額 12,000。",
      "D": "C 說了「raise」,在無限注中可加注任意金額。因為他宣告 15,000,必須補 1,500,讓 D 面對總額 15,000。",
    },
    optionsEn: {
      "A": "C declared \"raise\" then pushed out chips before stating an amount so his bet is based on the chip count. This makes it 13,500 total to Player D.",
      "B": "C said \"raise\" before declaring an amount so he is limited to a minimum raise. The min raise is 4000 (the big blind amount) making it a total of 10000 to D.",
      "C": "C said \"raise\" before declaring an amount so he is limited to a minimum raise. The min raise is 6000 (the largest prior bet or raise) making it a total of 12000 to D.",
      "D": "C said \"raise\" so he can raise any amount in no limit. Because he declared 15000 he must add 1500 to bring the total bet to D up to 15000",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 64,
    question: "關於攤牌時 A 要求看 B 的牌,下列何者為真?",
    questionEn: "Which of the following is true about Player A who asks to see the hand of Player B at showdown?",
    options: {
      "A": "這種要求是玩家想取得資訊的「鑽漏洞行為(angle shoot)」,絕不應准許。",
      "B": "若 B 是最後一輪下注中的最後攻擊者且 A 跟了 B 的注,A 有明確的看牌權。其他情況下由 TD 裁量。",
      "C": "看牌從來不是明確權利,TD 依情況決定是否准許。",
      "D": "要求看牌是為了保護賽局,牌局結束後必須准許。",
    },
    optionsEn: {
      "A": "Such a request is an angle shoot by a player trying to gain information. The request should never be granted.",
      "B": "Player A has an express right to see B's hand if B was the last aggressor on the final betting round and A called B's bet. In all other cases, TDs discretion applies.",
      "C": "There is never an express right to see a hand. The TD may or may not grant the request as he sees fit.",
      "D": "Asking to see a hand protects the game. The request must be honored after the hand is over.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 65,
    question: "新一手德州撲克開始,荷官正在發起手底牌。發牌過程中,有新玩家到 Seat 4 就座。新玩家到位後發現是誤發牌,起手底牌被收回並重新發。新玩家應該在重發時一起發牌。",
    questionEn: "A new hand of Texas Holdem starts and the dealer begins dealing the initial downcards. While he is dealing, a new player arrives to take Seat 4 at the table. After the player arrives a misdeal is discovered. The initial downcards are collected and the hand is re-dealt. The new player should be seated and dealt in on the re-deal.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 66,
    question: "德州撲克牌局剩 2 人,盲注 2,000/4,000。河牌時 A 開注 20,000,B 推出 4,000。應如何處理?",
    questionEn: "A texas holdem hand is down to two players. Blinds are 2,000 / 4,000. On the river Player A opens for 20,000. Player B pushes out 4,000. How should this be handled?",
    options: {
      "A": "因為是單挑(heads-up),B 可拿回跟注不足的籌碼重新考慮。若是多人牌局則必須補足 20,000。",
      "B": "B 對本輪開注做出跟注不足。儘管他誤解了,仍必須補足跟注、付到總額 20,000。",
      "C": "B 誤解下注,可自由選擇:拿回 4,000 棄牌、補足 20,000 跟注、或加注。",
      "D": "B 誤解開注,可選擇拿回 4,000 棄牌,或補足跟注 20,000,但不可加注。",
    },
    optionsEn: {
      "A": "Because play is heads-up, Player B can retrieve his undercall and re-consider. If play was multi-way he would be obligated for the full 20,000.",
      "B": "Player B has made an undercall to the opening bet of this round. Despite his misunderstanding, it is mandatory that Player B complete the call and put out a total of 20,000 chips.",
      "C": "Player B has misunderstood the bet and has all options open. He can take back his 4,000 and fold, make a call of 20,000 total, or raise.",
      "D": "Player B has misunderstood the opening bet. He can either retract his 4,000 and fold OR make a full call of 20,000; but he cannot raise.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 67,
    question: "德州撲克盲注 5000/10000。翻牌後小盲過牌,大盲在思考時 C 越位宣告「I'm all in for 52 thousand」。行動退回給大盲,大盲不發一語推出一個 10,000 籌碼。此時 C 有哪些下注選項?",
    questionEn: "In Texas Holdem blinds are 5000/10000. Postflop the SB checks. The BB is thinking when Player C declares out of turn \"I'm all in for 52 thousand\". Action backs up to the BB who then pushes out a 10,000 chip silently. What are the betting options for C at this point?",
    options: {
      "A": "C 已宣告全下,唯一選項就是把 52,000 全下。",
      "B": "C 可自由選擇:跟注 10,000、加注任何合法金額、或棄牌。",
      "C": "C 有兩個選項:跟注 10,000 或全下。不可加注其他金額,也不可棄牌。",
      "D": "C 必須跟注最高至 52,000。大盲下注 10,000,所以 C 必須跟注 10,000,這是唯一選項,不可加注或棄牌。",
    },
    optionsEn: {
      "A": "C has declared all-in. His only option is to push his entire stack of 52,000 all-in here.",
      "B": "C has all options open. He may call 10,000, raise any legal amount, or fold.",
      "C": "C has two options: either call 10,000 or go all-in. He may not raise another amount or fold.",
      "D": "C must call any bet up to 52,000. Because the BB bet 10,000, C must call the 10,000. This is his only option, he may not raise or fold.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 68,
    question: "德州撲克中,某桌比人數最多的桌少 3 人。盲注已付、起手底牌已發。荷官在有效動作發生前發現該桌人數不足。若不在此時暫停牌局,即為誤發牌。TD 必須宣告誤發牌並暫停牌局直到桌數平衡。",
    questionEn: "In texas holdem, a table is 3 players short of the table with the most players. Blinds are posted and the dealer has dealt the initial downcards. The dealer then recognizes the player shortfall before substantial action has occurred. Failing to halt play here is always a misdeal. The TD must declare a misdeal and halt play until the tables can be balanced.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 69,
    question: "下列哪些是官方的下注用語?(複選)額外選項:E. \"That's okay\" F. \"Check\" G. \"That's not enough\"",
    questionEn: "Which of the following are official betting terms? | Additional visible options: E. \"That's okay\" F. \"Check\" G. \"That's not enough\"",
    options: {
      "A": "我要下注",
      "B": "跟注",
      "C": "加注",
      "D": "推了",
      "E": "沒事",
      "F": "過牌",
      "G": "這不夠",
    },
    optionsEn: {
      "A": "\"I bet\"",
      "B": "\"Call\"",
      "C": "\"Raise\"",
      "D": "\"Push it\"",
      "E": "\"That's okay\"",
      "F": "\"Check\"",
      "G": "\"That's not enough\"",
    },
    answer: "BCF",
    multiSelect: true,
  },
  {
    id: 70,
    question: "7 張 Stud 中,A 不在座位上時荷官開始洗牌(riffle)。A 在最後一張起手明牌發出之前剛回到座位。應如何處理?額外選項:E. A 在起手第一張發牌時不在座位上,手牌作廢。",
    questionEn: "In 7-stud, Player A is away from the table when the dealer begins riffling cards for this hand. A returns and is at his seat just prior to the last initial upcard being dealt. How should this situation be handled? | Additional visible option: E. A was not at his seat when the first card was dealt on the initial deal. His hand is dead.",
    options: {
      "A": "A 在起手第一張發牌時不在座位上,所以一開始就不該發牌給他。",
      "B": "A 在第一次洗牌時不在座位上,所以一開始就不該發牌給他。",
      "C": "A 在第一次洗牌時不在座位上,所以發完所有座位後手牌作廢,這樣其他玩家才能拿到正確的起始牌且每人都付底注。",
      "D": "A 在所有起手牌發完前就回到座位,所以手牌算活的。",
      "E": "A 在起手第一張發牌時不在座位上,手牌作廢。",
    },
    optionsEn: {
      "A": "A was not at his seat when the first initial card was dealt, therefore A should have been dealt out of this hand.",
      "B": "Player A was not at his seat at the first riffle therefore he should have been dealt out of this hand.",
      "C": "A was not at his seat for the first riffle therefore his hand will be killed after cards are dealt to all seats in order that players receive correct starting cards & all players contribute an ante.",
      "D": "A was at his seat before all initial cards were dealt, therefore he has a live hand.",
      "E": "A was not at his seat when the first card was dealt on the initial deal. His hand is dead.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 71,
    question: "桌子被拆掉、所有玩家被移到別桌時,可被分配到哪些座位?在哪些座位可以立即收到牌?",
    questionEn: "When a table is broken (closed) and all its' players are moved to other tables, what seats may be assigned to the moved players and at what seats can they immediately receive a hand?",
    options: {
      "A": "可坐任何座位並立即收牌,但小盲位以及「小盲與按鈕之間」的位置除外。",
      "B": "可坐大盲位或大盲左側任何座位(包含 Button)並立即收牌。",
      "C": "可坐任何空位。除了「小盲與按鈕之間」的位置外,任何座位都可立即拿到牌。",
      "D": "因為原桌已拆,可在新桌任何空位就座並立即收牌。",
    },
    optionsEn: {
      "A": "They can sit and receive a hand at any seat except the small blind or between the small blind and button.",
      "B": "They can sit and receive a hand at the big blind or any seat to the left of the BB including the button.",
      "C": "They can sit at any open seat. They can receive a hand at any seat except between the small blind and button.",
      "D": "Because the old table is broken, they can sit and receive a hand at any open seat at the new table.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 72,
    question: "進行惡意送碼(chip dumping)或其他串通行為的玩家必須被取消資格。",
    questionEn: "Players who engage in chip dumping or other collusion must be disqualified.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 73,
    question: "無限注德州撲克盲注 100/200。翻牌後 A 開注 5000,B 加注至 9000,C、D 各跟 9000,E 棄牌。然後才發現 9000 比最小加注少 1000。應如何處理?",
    questionEn: "NLHE 100/200 blinds. Post-flop Player A opens for 5000 and Player B raises to 9000. Players C and D call the 9000 and Player E folds. Then it's noticed that 9000 is 1000 short of a minimum raise. How should this be handled?",
    options: {
      "A": "B 的不足加注更正為 10,000。C 與 D 可選跟足 10,000 或拿回 9,000 棄牌。E 的棄牌具約束力。",
      "B": "不足加注後已有至少兩位玩家行動(至少一位投入籌碼),已構成有效動作。之後不足加注具約束力,不更正為 10,000。後續再加注必須至少多 4,000。",
      "C": "不足加注後已有至少兩位玩家行動(至少一位投入籌碼),已構成有效動作。之後不足加注具約束力,不更正為 10,000。但後續再加注必須至少多 5,000。",
      "D": "因為下一條街尚未發出,B、C、D 的不足加注都更正為 10,000。E 的棄牌具約束力。",
    },
    optionsEn: {
      "A": "B's underraise will be corrected to 10,000. Players C and D have the option to call the full 10,000 or get their 9,000 back and fold. E's fold is binding.",
      "B": "Substantial action has occurred after the underraise by at least two players acting, at least one with chips. After substantial action the underraise is binding and will not be corrected to 10,000 total. Any re-raise must be at least 4000 more.",
      "C": "Substantial action has occurred after the underraise by at least two players acting, at least one with chips. After substantial action the underraise is binding and will not be corrected to 10,000 total. However any re-raise must be at least 5000 more.",
      "D": "Because the next street has not been dealt, the underraise will be corrected to 10,000 for B, C, and D. E's fold is binding.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 74,
    question: "桌上禁止任何時候講手機。",
    questionEn: "Talking on a cellphone is prohibited at the table at any time.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 75,
    question: "德州撲克 3 名玩家。翻牌後 A 全下,B 與 C 都跟注。轉牌時 B 全下,C 跟注(C 籌碼明顯比 B 多)。接下來應該怎麼做?",
    questionEn: "3 players in Texas Holdem. Post-flop Player A goes all-in and both B and C call. On the turn B goes all-in and C calls. C clearly has B covered. Which of the following should happen next:",
    options: {
      "A": "燒牌、開河牌。因為 B、C 在邊池中,先亮 B、C 的牌。邊池分配完後再亮 A 的牌決定主池。",
      "B": "在荷官燒牌、開河牌、進入攤牌前,3 名玩家都應該先把底牌翻開。",
      "C": "燒牌、開河牌。因為已無下注,Button 左邊第一位玩家應先亮牌。",
      "D": "燒牌、開河牌,然後進入攤牌,請玩家亮牌。",
    },
    optionsEn: {
      "A": "Burn and turn the river. Then because B & C are in the sidepot their cards are tabled first. After the sidepot is awarded, A's cards should be exposed to see who wins the main pot.",
      "B": "All 3 players should turn their downcards face up before the dealer burns and turns the river and moves to showdown.",
      "C": "Burn and turn the river. Then because there is no more betting the first player to the left of the button must show first.",
      "D": "Burn and turn the river then go to showdown and ask players to reveal their hands.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 76,
    question: "為了公平,晚到報名的玩家應按其錯過的盲注數扣減起始籌碼後再發放籌碼。",
    questionEn: "In the interest of fairness, a player registering late should be sold a starting chip-stack that has been reduced by the number of blinds he has missed since the beginning of the tournament.",
    options: {
      "A": "正確",
      "B": "錯誤",
    },
    optionsEn: {
      "A": "True",
      "B": "False",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 77,
    question: "盲注 500/1000 已下、新一手牌已開始發牌。C 加注至總額 4000,D 跟注,然後發現有誤發牌條件(除汙牌外的任何誤發牌條件)。應如何處理?為什麼?",
    questionEn: "500/1000 blinds are posted and cards are dealt for a new hand. Player C raises to 4000 total and D calls then a misdeal condition is noted (any misdeal condition other than a fouled deck) How should this be handled and why?",
    options: {
      "A": "已發生誤發牌:收回所有牌、退回下注、重洗、重新開始這手。",
      "B": "C 加注、D 跟注已構成有效動作,不能宣告誤發牌,牌局繼續。",
      "C": "TDA 把有效動作的定義交給場館決定,適用場館規定。",
    },
    optionsEn: {
      "A": "A misdeal has occurred: collect all cards, return all bets, re-shuffle and start the hand again.",
      "B": "Player C raising and D calling constitutes substantial action. A misdeal cannot be declared: proceed with the hand.",
      "C": "The TDA leaves the definition of substantial action up to house policy. House rules apply.",
    },
    answer: "B",
    multiSelect: false,
  },
  {
    id: 78,
    question: "許多玩家被淘汰後,TD 發現有許多大籌碼堆越來越難管理。TD 何時可導入升值併籌碼(color up)?",
    questionEn: "Numerous players are knocked out of a tournament and the TD notices there are many large chipstacks that are becoming difficult to manage. When can the TD introduce a color up?",
    options: {
      "A": "TD 可在任何時候依其裁量進行升值併籌碼。但應通知所有賽事參賽者。",
      "B": "非常大的籌碼堆能增加遊戲戲劇張力,深受玩家與觀眾喜愛,TDA 嚴禁裁量性升值併籌碼。",
      "C": "只有當某桌玩家自行提出時才能進行升值併籌碼。",
      "D": "只能在預定的升值併籌碼時間進行,依 TDA 規則進行籌碼賽馬(race off)。",
    },
    optionsEn: {
      "A": "The TD may color-up at any time at his or her discretion. The color up should be announced to all participating in the tournament.",
      "B": "Very large chipstacks add to the drama and excitement of the game and are appreciated by players and viewers alike. Hence discretionary color-ups are strongly discouraged by the TDA",
      "C": "The TD may only color up at the request of players at a table where the unwieldy stacks are becoming a problem.",
      "D": "At scheduled color-ups only. Chips will be raced off as provided by TDA Rules.",
    },
    answer: "A",
    multiSelect: false,
  },
  {
    id: 79,
    question: "德州撲克盲注 1000/2000。翻牌後 A 開注 6000,B 正在思考時,荷官接著未注意到 B 還沒行動,讓 C 跟、D 棄。然後才發現 B 尚未行動。應如何處理?",
    questionEn: "In texas holdem, blinds 1000/2000, post-flop Player A opens for 6000. Player B is thinking when dealer then recognizes that B has not acted. What should happen?",
    options: {
      "A": "依 TDA 規則,B 只能跟 6,000 或棄牌,不可加注。",
      "B": "荷官應掌控桌面,把所有越序行動視為不具約束力,問 B 想做什麼。C、D 行動權保留。",
      "C": "D 的棄牌有約束力。行動退回 B。若 B 棄或跟 A 的 6,000,則 C 鎖定在其跟注。若 B 加注,則 C 解除約束,可跟、加或棄。",
      "D": "已發生越序的有效動作。C、D 的行動現具約束力。叫 TD 來決定 B 的手牌如何處理。",
    },
    optionsEn: {
      "A": "Under TDA Rules, player B may only call the 6,000 or fold, he cannot raise.",
      "B": "The dealer should take control of the table, rule all out-of-turn action non-binding, and ask Player B what he would like to do. Players C and D have all options open.",
      "C": "Player D's fold is binding. The action should be backed up to Player B. If Player B folds or calls Player A's 6000 then Player C is locked into his call. Otherwise if Player B raises then Player C is released and may call, raise, or fold.",
      "D": "Substantial action has occurred out of turn. The action by Players C and D is now binding. The TD will be called to render a decision on how to treat Player B's hand.",
    },
    answer: "D",
    multiSelect: false,
  },
  {
    id: 80,
    question: "升值併籌碼時,所有 100 及更低面額籌碼被移除。事後,場上最低面額為 500。牌局繼續一段時間後,發現某玩家還持有 9 個 100 籌碼(共 900)。應如何處理?",
    questionEn: "During a color-up, all denominations 100 and lower are removed. After, the smallest denomination in play is a 500 chip. Play resumes then it is noticed that one player still has nine 100-value chips (a total of 900). What should happen?",
    options: {
      "A": "100 籌碼已不在賽事中,應從桌上移除。玩家有責任注意升值併籌碼,不予補償。",
      "B": "應以場上最低面額補償到最接近的金額,玩家領兩個 500 籌碼。",
      "C": "其中 5 個 100 換成 1 個 500,其餘 4 個 100 移除、不補償。",
    },
    optionsEn: {
      "A": "The 100 chip is no longer in play and should be removed from the table. Players are responsible for observing the color-up and will not be compensated.",
      "B": "Players should be compensated to the next nearest amount using the lowest denomination in play. Player receives two 500's.",
      "C": "Five of the 100 chips will be exchanged for a 500 chip. The other four 100-value chips will be removed without compensation.",
    },
    answer: "C",
    multiSelect: false,
  },
  {
    id: 81,
    question: "一名不在牌局中的玩家誤以為荷官在攤牌時誤判牌型。他大聲說了出來讓所有人聽到,然後才意識到自己搞錯了。TD 應如何處理?",
    questionEn: "A player not involved in the hand mistakenly thinks the dealer mis-read a hand at showdown. The player speaks out loud for all to hear then realizes his mistake. How should the TD handle this?",
    options: {
      "A": "鼓勵所有玩家(無論是否在牌中)解讀已亮出的牌,並在覺得有誤時出聲。本題不予處罰。",
      "B": "必須執行「獨立手牌」規則,至少跳一手的處罰。本題不可用警告處置。",
      "C": "只有參與攤牌的玩家才能對牌型解讀發表意見。該玩家不在牌中,TD 可酌情警告或處罰。",
      "D": "必須執行「獨立手牌」規則。TD 應酌情警告或處罰該玩家。",
    },
    optionsEn: {
      "A": "All players whether in the hand or not are encouraged to read tabled hands and speak up if they think an error is being made. No penalty is in order here.",
      "B": "The one-player-to-a-hand rule must be enforced and requires at least a one-hand penalty. A warning is not an option in this case.",
      "C": "Only players involved in the showdown are allowed to comment about reading of the hands. Since this player was not involved, the TD may warn or penalize as he sees fit.",
      "D": "The one-player-to-a-hand rule must be enforced. The TD should warn or penalize the player as he sees fit.",
    },
    answer: "A",
    multiSelect: false,
  },
];
